"""게임 도메인 정의 (피자 레디 mock).

기존 게임 분석 흐름을 그대로 보존한 도메인 설정. 12 개 mock 테이블 화이트리스트와
4 개 segmentable KPI 는 ``analysis-performance`` 묶음의 정비 결과를 따른다.
"""

from __future__ import annotations

from datapilot.domain.base import DomainConfig, DomainKeywords, UILabels

GAME = DomainConfig(
    name="game",
    db_path="data/mock/game.db",
    allowed_tables=frozenset({
        "daily_kpi",
        "users",
        "products",
        "payments",
        "shop_impressions",
        "releases",
        "events",
        "sessions",
        "content_releases",
        "gateways",
        "payment_attempts",
        "payment_errors",
    }),
    supported_segment_metrics=frozenset({
        "revenue",
        "dau",
        "payment_success_rate",
        "d7_retention",
    }),
    table_descriptions={
        "daily_kpi": "일별 KPI 집계 (Bottleneck Detector 입력)",
        "users": "유저 마스터 (세그먼트 차원: platform, country, user_type, device_model)",
        "products": "상품 마스터 (price_tier, category). 상품별 가격대 확인",
        "payments": "결제 이벤트 (user_id, product_id, amount, status, timestamp). 유저별 결제 내역 추적",
        "shop_impressions": "상점 진열 노출 로그 (product_id, slot_order, platform, date). 앱 업데이트 전후 상품 진열 순서 변화 분석에 활용",
        "releases": "앱 빌드 배포 이력 (platform, version, released_at, build_notes). 특정 날짜 배포와 이상 시점 연관 분석",
        "events": "인게임 이벤트 로그 (user_id, event_type: login/stage_clear/purchase/event_participate, event_time)",
        "sessions": "세션 로그 (user_id, session_start, session_end). 리텐션·활성화 분석",
        "content_releases": "컨텐츠/이벤트 스케줄 (content_type, name, start_date, end_date). 이벤트 종료 시점과 지표 변화 연관 분석",
        "gateways": "PG사 정보 (name, region, status: active/degraded/down). PG사 장애 상태 확인",
        "payment_attempts": "결제 시도 로그 (user_id, gateway, status: success/failed, attempt_time). 게이트웨이별 성공률 분석",
        "payment_errors": "결제 에러 상세 (error_code, error_message, gateway, first_seen). PG사별 에러 패턴 추적",
    },
    viewer_table_descriptions={
        "daily_kpi": "날짜별 핵심 지표 모음 — 하루치 매출 / 유저 수 / 리텐션 등",
        "users": "유저 정보 — 플랫폼 / 국가 / 유저 유형 / 기기 등 기본 정보",
        "products": "상품 정보 — 인앱 상품 목록 (이름 / 가격대 / 카테고리)",
        "payments": "결제 기록 — 누가 / 언제 / 얼마짜리 상품을 샀는지 한 건씩",
        "shop_impressions": "상점 노출 기록 — 어느 유저에게 어느 상품이 몇 번째 칸에 보였는지",
        "releases": "앱 출시 이력 — 플랫폼별 새 버전 배포 시점",
        "events": "인게임 행동 로그 — 로그인 / 스테이지 클리어 / 결제 등 이벤트 한 건씩",
        "sessions": "접속 세션 로그 — 한 유저가 언제 들어와서 언제 나갔는지",
        "content_releases": "이벤트 / 컨텐츠 일정 — 시즌 이벤트 시작 · 종료 시점",
        "gateways": "결제사 정보 — PG(결제 대행)사 이름과 현재 상태 (정상 / 장애)",
        "payment_attempts": "결제 시도 로그 — PG 별로 성공했는지 실패했는지 시도 한 건씩",
        "payment_errors": "결제 에러 상세 — 어떤 에러 코드가 어느 PG 에서 처음 나타났는지",
    },
    column_descriptions={
        "content_releases": {
            "content_id": "컨텐츠 식별자",
            "content_type": "컨텐츠 종류 (시즌 이벤트 / 한정 패키지 등)",
            "name": "컨텐츠 이름",
            "start_date": "시작일",
            "end_date": "종료일",
        },
        "daily_kpi": {
            "date": "날짜",
            "dau": "일간 활성 유저 수 - 해당 일에 한 번이라도 접속한 유저 수",
            "mau": "월간 활성 유저 수 - 해당 일 기준 최근 30일 내 한 번이라도 접속한 유저 수",
            "revenue": "매출 (원) - 해당 일에 결제 완료된 금액의 합계",
            "arppu": "결제 유저 1명당 평균 매출 (원) - 해당 일 매출을 결제한 유저 수로 나눈 값",
            "d1_retention": "다음 날 재방문률 (0~1) - 해당 일 신규 설치 유저 중 다음 날에도 접속한 비율",
            "d7_retention": "7일 후 재방문률 (0~1) - 해당 일 신규 설치 유저 중 7일 후에도 접속한 비율",
            "sessions": "접속 세션 수 - 해당 일에 발생한 접속 세션의 총 개수",
            "avg_session_sec": "평균 접속 시간 (초)",
            "payment_success_rate": "결제 성공률 (0~1) - 해당 일 결제 시도 대비 성공 비율",
            "new_installs": "신규 설치 수",
        },
        "events": {
            "event_id": "이벤트 식별자",
            "user_id": "유저 식별자",
            "event_type": "이벤트 종류 (login / stage_clear / purchase / event_participate)",
            "event_time": "이벤트 발생 시각",
            "metadata": "부가 정보 (이벤트별 상세, JSON 문자열)",
        },
        "gateways": {
            "gateway_id": "PG사 식별자",
            "name": "PG사 이름",
            "region": "서비스 지역",
            "status": "현재 상태 (active = 정상 / degraded = 불안정 / down = 장애)",
        },
        "payment_attempts": {
            "attempt_id": "결제 시도 로그 식별자",
            "user_id": "유저 식별자",
            "gateway": "사용한 PG",
            "attempt_time": "시도 시각",
            "status": "시도 결과 (success = 성공 / failed = 실패)",
            "error_code": "실패 시 에러 코드 (성공 시 비어있음)",
        },
        "payment_errors": {
            "error_code": "에러 코드",
            "error_message": "에러 메시지",
            "gateway": "발생 PG",
            "first_seen": "처음 나타난 시각",
        },
        "payments": {
            "payment_id": "결제 식별자",
            "user_id": "결제한 유저",
            "product_id": "결제한 상품",
            "amount": "결제 금액 (원)",
            "timestamp": "결제 시각",
            "status": "결제 상태",
        },
        "products": {
            "product_id": "상품 식별자",
            "name": "상품 이름",
            "price_tier": "가격대 (low / mid / high 등)",
            "category": "상품 카테고리",
        },
        "releases": {
            "release_id": "배포 식별자",
            "version": "앱 버전",
            "platform": "플랫폼 (iOS / Android)",
            "released_at": "배포 시각",
            "build_notes": "배포 노트 (변경 사항 요약)",
        },
        "sessions": {
            "session_id": "세션 식별자",
            "user_id": "접속한 유저",
            "session_start": "접속 시작 시각",
            "session_end": "접속 종료 시각",
            "platform": "접속 플랫폼",
        },
        "shop_impressions": {
            "impression_id": "노출 식별자",
            "user_id": "노출 받은 유저",
            "product_id": "노출된 상품",
            "impression_time": "노출 시각",
            "slot_order": "진열 순서 (몇 번째 칸에 보였는지)",
        },
        "users": {
            "user_id": "유저 식별자",
            "platform": "플랫폼 (iOS / Android)",
            "country": "국가",
            "user_type": "유저 유형 (paid / free 등)",
            "install_date": "첫 설치일",
            "device_model": "기기 모델",
        },
    },
    ui_labels=UILabels(
        industry_name="게임",
        entity_default_id="pizza_ready",
        kpi_korean={
            "dau": "일간 활성 유저",
            "mau": "월간 활성 유저",
            "revenue": "매출",
            "arppu": "결제 유저 평균 매출",
            "d1_retention": "D1 리텐션",
            "d7_retention": "D7 리텐션",
            "sessions": "세션 수",
            "avg_session_sec": "평균 세션 길이",
            "payment_success_rate": "결제 성공률",
            "new_installs": "신규 설치",
        },
        scenario_descriptions=(
            "결제 성공률 급락 (PG 장애 — 브라질)",
            "Android 상점 UI 패치 영향",
        ),
    ),
    agent_keywords=DomainKeywords(
        persona="게임 PM",
        role_descriptor="게임 운영 데이터 분석가",
        primary_kpis=("DAU", "ARPPU", "리텐션", "매출", "결제 성공률"),
    ),
)